Split stuff into functions and a library

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -31,67 +31,80 @@ PATH=/bin:/usr/bin:${PATH}
 # Read the OpenShift functions
 source ${OPENSHIFT_CARTRIDGE_SDK_BASH}
 
-# Set constants
-VERSION="${1:-14.3}"
-PLANON="${OPENSHIFT_PLN_DIR}}/PlanonProCenter"
-JBOSS="${PLANON}/jboss-6.1.0.Final"
-TOMCAT="${PLANON}/tomcat-7.0.47"
+# Set constants and read constants
+LIBDIR="${CRD}/../lib"
+LIBRARY="${LIBDIR}/library"
+[[ ! -r ${LIBRARY} ]] && { echo "${LIBRARY} not found"; exit 1; }
+. ${LIBRARY} || { echo "Error reading ${LIBRARY}"; exit 1; }
+
+# Get the commandline options
+version=""
+case "${1}" in
+	-v|--version)
+		version="${2}"
+		;;
+esac
+
+if [[ x"${version}" == x"" ]]
+then
+	status "0" "Install called without extra version info"
+else
+	status "0" "Install called with version ${version}"
+fi
 
 
-# Return date/time in standard format
-now()
-{
-	date '+%Y-%m-%d %H:%M:%S'
-}
+# Check if the process is running
+# ${1} is the PID file for the app (Tomcat / JBoss)
+isrunning() {
+	PIDFILE="${1}"
 
-
-# Get a file from the web
-get()
-{
-	SRC="${1}"
-	DST="${2}"
-
-	wget --http-user=cockpit 			\
-		--http-password=test1234 		\
-		--output-document="${DST}" 		\
-	 	"${SRC}"
-
-	 return ${?}
-}
-
-
-# Display a status message
-status()
-{
-	RC="${1}"
-	shift
-	message="${*}"
-
-	[[ ${RC} == 0 ]] && STATTXT="OK " || STATTXT="ERR"
-	str="$(printf -- "%s - %-3d - %s - %s\n" "$(now)" "${RC}" "${STATTXT}" "${message}")"
-
-	printf -- "${str}" >&2
-	if [[ x"${RC}" == x"0" ]]
+	# Check for running app
+	if [[ -f "${PIDFILE}" ]]
 	then
-		client_result "${str}"
-	else
-		client_error "${str}"
+		running=$(/bin/ps --no-headers --pid $(<${PIDFILE}))
+		if [[ x"${running}" = x"" ]]
+		then
+			# Not running
+			return 1
+		else
+			# running
+			return 0
+		fi
 	fi
+
+	# No PID file. Not running
+	return 1
 }
 
 
 # Start all services
 start()
 {
-	status "0" "start"
-	status "0" "	Start openshift cartridge runtime"
+	typeset -i RC=0
+	showstatus "0" "start"
+	showstatus "0" "	Start openshift cartridge runtime"
 
 	cp ${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml ${JBOSS}/server/default/deploy
 
+	# Check if JBoss is running
+	if running ${JBOSSPID}
+	then
+		showstatus "1" "Program JBoss is already running"
+		return 1
+	fi
 
+	# Check if Tomcat is running
+	if running ${TOMCATPID}
+	then
+		showstatus "1" "Program Tomcat is already running"
+		return 1
+	fi
+	# Come here, nothing is running
+
+	# Copy database XML
 	if [[ ! -s "${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml" ]]
 	then
-		status "0" "	No DB connection string found, give it a new try"
+		showstatus "0" "	No DB connection string found, give it a new try"
 		get ${PLANON_COCKPIT_URL}/Database/${OPENSHIFT_APP_DNS} ${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml
 		if [[ -s "${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml" ]]
 		then
@@ -101,62 +114,116 @@ start()
 
 	if [[ -s "${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml" ]]
 	then
-		status "0" "	Starting......."
+		showstatus "0" "	Starting......."
 
 		source ${OPENSHIFT_PLN_DIR}/conf/jboss_settings
 		nohup ${JBOSS}/bin/run.sh -H ${OPENSHIFT_PLN_IP} -b ${OPENSHIFT_PLN_IP} &
+		echo "${!}" > ${JBOSSPID}
 
 		source ${OPENSHIFT_PLN_DIR}/conf/tomcat_settings
 		nohup ${TOMCAT}/bin/startup.sh &
+		echo "${!}" > ${TOMCATPID}
 	else
-		status "1" "	Cannot start, still no DB available"
+		showstatus "1" "	Cannot start, still no DB available"
 	fi
-	status "0" "trats"
+	showstatus "0" "trats"
 }
 
 
 # Stop all services
 stop()
 {
-	status "0" "	Stop openshift cartridge runtime"
-	${TOMCAT}/bin/shutdown.sh
-	status "${?}" "TomCat shutdown"
-	${JBOSS}/bin/shutdown.sh --host=${OPENSHIFT_PLN_IP}
-	status "${?}" "JBoss shutdown"
+	typeset -i RC=0
+
+	showstatus "0" "	Stop openshift cartridge runtime"
+
+	# Check if JBoss is running
+	if running ${JBOSSPID}
+	then
+		${TOMCAT}/bin/shutdown.sh
+	else
+		showstatus "1" "Program JBoss is already stopped"
+		RC=RC+1
+	fi
+
+	# Check if Tomcat is running
+	if running ${TOMCATPID}
+	then
+		${JBOSS}/bin/shutdown.sh --host=${OPENSHIFT_PLN_IP}
+	else
+		showstatus "1" "Program Tomcat is already stopped"
+		RC=RC+1
+	fi
+
+	return ${RC}
 }
 
 
 # Restart all services
 restart()
 {
-	stop
+	typeset RC=0
+
+	stop	|| RC=RC+1
 	sleep 2
-	start
+	start	|| RC=RC+1
+
+	return ${RC}
+}
+
+
+# Display the status of the services
+status()
+{
+	typeset RC=0
+	# Check if JBoss is running
+	if running ${JBOSSPID}
+	then
+		showstatus "0" "	JBoss is running"
+	else
+		showstatus "1" "	JBoss is NOT running"
+		RC=RC+1
+	fi
+
+	# Check if Tomcat is running
+	if running ${TOMCATPID}
+	then
+		showstatus "0" "	Tomcat is running"
+	else
+		showstatus "1" "	Tomcat is NOT running"
+		RC=RC+1
+	fi
+
+	return ${RC}
 }
 
 
 catchall()
 {
-	status "1" "	${1}: not yet implemented"
+	showstatus "1" "	${1}: not yet implemented"
+
+	return 0
 }
 
 
-status "0" "Control Main called ${VERSION}"
+showstatus "0" "Control Main called ${version}"
 case "${1}"
 in
-	start)					start    ;;
-	stop)					stop     ;;
-	restart)				restart  ;;
-	status)					catchall ;;
-	deploy)					catchall ;;
-	reload)					catchall ;;
-	tidy)					catchall ;;
-	pre-build)				catchall ;;
-	build)					catchall ;;
-	post-deploy)			catchall ;;
-	pre-repo-archive)		catchall ;;
-	update-configuration)	catchall ;;
+	start)					start		;;
+	stop)					stop		;;
+	restart)				restart		;;
+	status)					status		;;
+	deploy)					catchall	;;
+	reload)					catchall	;;
+	tidy)					catchall	;;
+	pre-build)				catchall	;;
+	build)					catchall	;;
+	post-deploy)			catchall	;;
+	pre-repo-archive)		catchall	;;
+	update-configuration)	catchall	;;
 	*)						exit 0
 esac
 
-exit 0
+# Exit. No exit code!! The exit code will be the exit code
+# of the last run process!!
+exit
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -25,11 +25,15 @@ set +o noclobber		# Overwrite existing files, if needed
 set -o nounset			# Don't allow uninitialized variables
 set +o errexit			# No returncode checking
 
-# Set the PATH
-PATH=/bin/:/usr/bin:${PATH}
-
 # Read the OpenShift functions
 source ${OPENSHIFT_CARTRIDGE_SDK_BASH}
+
+# Set constants and read constants
+LIBDIR="${CRD}/../lib"
+LIBRARY="${LIBDIR}/library"
+[[ ! -r ${LIBRARY} ]] && { echo "${LIBRARY} not found"; exit 1; }
+. ${LIBRARY} || { echo "Error reading ${LIBRARY}"; exit 1; }
+
 
 # Program usage
 usage()
@@ -46,46 +50,6 @@ usage()
 }
 
 
-# Return date/time in standard format
-now()
-{
-	date '+%Y-%m-%d %H:%M:%S'
-}
-
-
-# Display a status message
-status()
-{	RC="${1}"
-	shift
-	message="${*}"
-
-	[[ ${RC} == 0 ]] && STATTXT="OK " || STATTXT="ERR"
-	str="$(printf -- "%s - %-3d - %s - %s\n" "$(now)" "${RC}" "${STATTXT}" "${message}")"
-
-	printf -- "${str}" >&2
-	if [[ x"${RC}" == x"0" ]]
-	then
-		client_result "${str}"
-	else
-		client_error "${str}"
-	fi
-}
-
-# Get a file from the web
-get()
-{
-	SRC="${1}"
-	DST="${2}"
-
-	wget --http-user=cockpit 			\
-		--http-password=test1234 		\
-		--output-document="${DST}" 		\
-	 	"${SRC}"
-
-	 return ${?}
-}
-
-
 # Get the commandline options
 version=""
 case "${1}" in
@@ -96,40 +60,32 @@ esac
 
 if [[ x"${version}" == x"" ]]
 then
-	status "0" "Install called without extra version info"
+	showstatus "0" "Install called without extra version info"
 else
-	status "0" "Install called with version ${version}"
+	showstatus "0" "Install called with version ${version}"
 fi
 
-# Define constants
-DOWNLOAD_FILE_JBOSS="${version}-jboss.zip"
-DOWNLOAD_FILE_TOMCAT="${version}-tomcat.zip"
-DOWNLOAD_LOCATION="${PLANON_FILESERVER_URL}"
-
-JBOSS="PlanonProCenter/jboss-6.1.0.Final"
-JBOSS_DEF="${JBOSS}/server/default"
-TOMCAT="PlanonProCenter/tomcat-7.0.47"
 
 # We assume this directory exists
 cd ${OPENSHIFT_PLN_DIR}
 
 # Get the right DB connections
-status "0" "Request database connect string"
+showstatus "0" "Request database connect string"
 get ${PLANON_COCKPIT_URL}/Database/${OPENSHIFT_APP_DNS}/${version}	\
 	${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml
-status "${?}" "Request database executed name : ${OPENSHIFT_APP_DNS}"
+showstatus "${?}" "Request database executed name : ${OPENSHIFT_APP_DNS}"
 
-status "0" "Request webdav account"
+showstatus "0" "Request webdav account"
 get	${PLANON_COCKPIT_URL}/WebdavResource/${OPENSHIFT_APP_DNS}		\
 	${OPENSHIFT_PLN_DIR}/conf/tomcat-users.xml
-status "${?}" "JBoss download started"
+showstatus "${?}" "JBoss download started"
 
 get ${DOWNLOAD_LOCATION}/${DOWNLOAD_FILE_JBOSS}						\
 	${DOWNLOAD_FILE_JBOSS}
-status "${?}" "JBoss downloaded ended"
+showstatus "${?}" "JBoss downloaded ended"
 
 unzip -q $DOWNLOAD_FILE_JBOSS -d PlanonProCenter
-status "${?}" "JBoss unzipped"
+showstatus "${?}" "JBoss unzipped"
 
 rm ${DOWNLOAD_FILE_JBOSS}
 
@@ -141,16 +97,16 @@ cp ${OPENSHIFT_PLN_DIR}/conf/jndi.properties 	${JBOSS_DEF}/conf/
 cp ${OPENSHIFT_PLN_DIR}/conf/hornetq-jms.xml 	${JBOSS_DEF}/deploy/hornetq/
 #cp ${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml 	${JBOSS_DEF}/deploy
 
-status "0" "JBoss done!"
+showstatus "0" "JBoss done!"
 
 # TOMCAT
-status "0" "Tomcat download started"
+showstatus "0" "Tomcat download started"
 get ${DOWNLOAD_LOCATION}/${DOWNLOAD_FILE_TOMCAT} 					\
 	${DOWNLOAD_FILE_TOMCAT}
-status "${?}" "Tomcat downloaded ended"
+showstatus "${?}" "Tomcat downloaded ended"
 
 unzip -q ${DOWNLOAD_FILE_TOMCAT} -d PlanonProCenter
-status "${?}" "Tomcat unzipped"
+showstatus "${?}" "Tomcat unzipped"
 
 rm ${DOWNLOAD_FILE_TOMCAT}
 
@@ -170,7 +126,7 @@ chmod +x ${TOMCAT}/bin/catalina.sh
 chmod +x ${TOMCAT}/bin/shutdown.sh
 chmod +x ${TOMCAT}/bin/setenv.sh
 
-status "0" "Waiting for database to be ready."
+showstatus "0" "Waiting for database to be ready."
 
 # wait untill the database is ready stop after 30 seconds
 typeset -i COUNTER=0
@@ -182,7 +138,7 @@ do
 	echo "  Check if database is ready.($COUNTER)"
 	get ${PLANON_COCKPIT_URL}/Database/${OPENSHIFT_APP_DNS}			\
 		${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml
-	status "${?}" "Database XML downloaded"
+	showstatus "${?}" "Database XML downloaded"
 
 	if [[ ${COUNTER} -ge 30 ]]
 	then
@@ -192,9 +148,9 @@ done
 
 if [[ ! -s "${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml" ]]
 then
-	status "1" "    Database not ready, still taking a shot."
+	showstatus "1" "    Database not ready, still taking a shot."
 else
- 	status "0" "    Database is ready."
+ 	showstatus "0" "    Database is ready."
 	cp ${OPENSHIFT_PLN_DIR}/conf/planon-ds.xml ${JBOSS_DEF}/deploy
 fi
 
diff --git a/bin/teardown b/bin/teardown
--- a/bin/teardown
+++ b/bin/teardown
@@ -1,8 +1,56 @@
-#!/bin/bash -e
+#!/bin/bash
+# vi: set sw=4 ts=4 ai:
 
-PATH=/bin/:/usr/bin:$PATH
+# Determine the program name and the 'running directory'
+IAM="${0##*/}"
+CRD="$( [[ "${0:0:2}" = "./" ]] &&
+	{	printf "${PWD}/${0#./}"
+	} || {
+		printf "${0}"
+	})"
+CRD="${CRD%/*}"
+CUR="${PWD}"
 
-source $OPENSHIFT_CARTRIDGE_SDK_BASH
+# Make sure all language settings are correct
+export LANG=C
+
+# Save the shell settings
+SETA=0; [[ ${-} = *a* ]] && SETA=1
+SETE=0; [[ ${-} = *e* ]] && SETE=1
+SETU=0; [[ ${-} = *u* ]] && SETU=1
+SETX=0; [[ ${-} = *x* ]] && SETX=1
+
+# Set and unset the needed shell settings
+set +o noclobber		# Overwrite existing files, if needed
+set -o nounset			# Don't allow uninitialized variables
+set +o errexit			# No returncode checking
+
+# Set the PATH
+PATH=/bin:/usr/bin:${PATH}
+
+# Read the OpenShift functions
+source ${OPENSHIFT_CARTRIDGE_SDK_BASH}
+
+# Set constants and read constants
+LIBDIR="${CRD}/../lib"
+LIBRARY="${LIBDIR}/library"
+[[ ! -r ${LIBRARY} ]] && { echo "${LIBRARY} not found"; exit 1; }
+. ${LIBRARY} || { echo "Error reading ${LIBRARY}"; exit 1; }
+
+# Get the commandline options
+version=""
+case "${1}" in
+	-v|--version)
+		version="${2}"
+		;;
+esac
+
+if [[ x"${version}" == x"" ]]
+then
+	status "0" "Install called without extra version info"
+else
+	status "0" "Install called with version ${version}"
+fi
 
 client_result "Teardown called Main"
 
